### ISSUE TITLE
Should branches that were pulled into main be deleted?

### ISSUE THREAD

**Issue by Alliniska** [DCDLEAFY/DCDLEAFY.github.io#15]
For instance Ren branch no longer has function, so shouldn;t it at the least be deleted now?

**Comment by Alliniska** [comment]
Just realised I can delte them meself whoopsies, but still, when you merge something that has been completed like geoLocation delete it afterwards

**Comment by DCDLEAFY** [comment]
Yes after merge into main i will usually delete it although i have forgotten a few times.
