### ISSUE TITLE
New template for our repository

### ISSUE THREAD

**Issue by costingrigore** [DCDLEAFY/DCDLEAFY.github.io#4]
Hey guys,

I just wanted to let you all know that I have implemented a new template for our project.
I found this template in Mike Crabb's GitHub repository:
https://github.com/mikecrabb/AgileDevelopment_templateCWRepo
Many groups have been using it already, so I thought I would be a good idea to implement it too in our repositories.
I haven't uploaded the new template to master, as I think it is a good idea to wait for everyone to be on the same page.
I will give you more details tomorrow.

Thank you for your time,

Costin
[AgileDevelopment_templateCWRepo-master.zip](https://github.com/DCDLEAFY/DCDLEAFY.github.io/files/4130513/AgileDevelopment_templateCWRepo-master.zip)

**Comment by DCDLEAFY** [comment]
Forgot to say this but thank you! it has been done!
